version: "3.7"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_backbone
      - traefik.http.routers.n8n.rule=Host(`n8n.home.aquiver.de`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls.certresolver=wildcard-godaddy
      - traefik.http.routers.n8n.service=n8n-service@docker
      - traefik.http.services.n8n-service.loadbalancer.server.port=5678
#      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
#      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
#      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
#      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
#      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
#      - traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN_NAME}
#      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
#      - traefik.http.middlewares.n8n.headers.STSPreload=true
    environment:
      - N8N_HOST=n8n.home.aquiver.de
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.home.aquiver.de/
      - GENERIC_TIMEZONE=Europe/Berlin
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - internet
      - traefik_backbone

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
  traefik_backbone:
    name: traefik_backbone
    external: true
