version: "3"
services:
  db_recipes-init:
    image: postgres:15-alpine
    volumes:
      - ./postgresql:/data
    entrypoint:
      - sh
      - -c
      - |
        chown -R 1000:1000 /data

  db_recipes:
    depends_on:
      db_recipes-init:
        condition: service_completed_successfully
    restart: always
    image: postgres:15-alpine
    user: "1000:1000"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - no-internet


  web_recipes:
    restart: always
    image: vabene1111/recipes
    env_file:
      - ./.env
    environment:
      SOCIAL_PROVIDERS: "allauth.socialaccount.providers.openid_connect"
      SOCIALACCOUNT_PROVIDERS: '{"openid_connect": {"APPS": [{"provider_id": "pocketid","name": "Pocket ID","client_id": "10c2bd8d-d2e4-4e5d-90ab-f02e4144b91f","secret": "yOaAsuzQLGO2IowzUteSStt3hKyLxrny","settings": { "server_url": "https://auth.home.aquiver.de/.well-known/openid-configuration"}}]}}'
      SOCIALACCOUNT_LOGIN_ON_GET: 1
      ALLOWED_HOSTS: recipes.home.aquiver.de
      HIDE_LOGIN_FORM: 1
      SOCIALACCOUNT_ONLY: 1
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
    # depends_on:
    #   - db_recipes
    networks:
      - no-internet
      - internet
      - traefik_backbone

    labels: # traefik example labels
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_backbone"
      - "traefik.http.routers.recipes.entrypoints=websecure"
      - "traefik.http.routers.recipes.rule=Host(`recipes.home.aquiver.de`)"
      - "traefik.http.routers.recipes.tls=true"
      - "traefik.http.routers.recipes.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.recipes.service=recipes-service@docker"
      - "traefik.http.services.recipes-service.loadbalancer.server.port=80"

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
  traefik_backbone:
    name: traefik_backbone
    external: true


volumes:
  staticfiles:
