global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  wildcard-godaddy:
    acme:
      email: "daniel-habenich@outlook.de"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

