services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - no-internet

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      - no-internet

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
#    ports:
#      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_URL: https://documents.${SUBDOMAIN:-home}.aquiver.de
      PAPERLESS_CONSUMER_ENABLE_BARCODES: true # enable search for barcodes
      PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: true # enable setting ASN by ASN barcodes
      PAPERLESS_CONSUMER_BARCODE_SCANNER: ZXING # switch from pyzbar to zxing for better recognitio
      PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: '{"openid_connect": {"APPS": [{"provider_id": "pocketid","name": "Pocket ID","client_id": "${OIDC_CLIENT_ID}","secret": "${OIDC_CLIENT_SECRET}","settings": { "server_url": "https://auth.${SUBDOMAIN:-home}.aquiver.de/.well-known/openid-configuration"}}]}}'
      PAPERLESS_DISABLE_REGULAR_LOGIN: true
      PAPERLESS_REDIRECT_LOGIN_TO_SSO: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_backbone"
      - "traefik.http.routers.paperless.rule=Host(`documents.${SUBDOMAIN:-home}.aquiver.de`)"
      - "traefik.http.routers.paperless.service=paperless-service@docker"
      - "traefik.http.services.paperless-service.loadbalancer.server.port=8000"
      - "homepage.group=Dokumentenverwaltung"
      - "homepage.name=Paperless NGX"
      - "homepage.icon=sh-paperless-ngx"
      - "homepage.href=https://documents.${SUBDOMAIN:-home}.aquiver.de"
    networks:
      - no-internet
      - traefik_backbone

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.24
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - no-internet

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
    networks:
      - no-internet

  pdfedit:
    image: ghcr.io/danielhabenicht/danielhabenicht/fork.pdf-web-edit:v0.9.6
    restart: unless-stopped
    volumes:
      - ./pdf-edit-config/:/config
      - ./pdf-edit-inbox/:/inbox
      - ./consume/:/outbox
      - ./pdf-edit-archive/:/archive
    user: '1000:1000'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_backbone"
      - "traefik.http.routers.pdfedit.entrypoints=websecure"
      - "traefik.http.routers.pdfedit.rule=Host(`import.${SUBDOMAIN:-home}.aquiver.de`)"
      - "traefik.http.routers.pdfedit.tls=true"
      - "traefik.http.routers.pdfedit.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.pdfedit.service=pdfedit-service@docker"
      - "traefik.http.services.pdfedit-service.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.limit.buffering.memRequestBodyBytes=4000000"
    networks:
      - no-internet
      - traefik_backbone

  sftp:
    image: atmoz/sftp
    volumes:
      - ./consume:/home/paperless/upload
      - ./keys/publickey.pub:/home/paperless/.ssh/keys/publickey.pub:ro
      - ./keys/host/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - ./keys/host/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./keys/host/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub:ro
    ports:
      - "2222:22"
    command: paperless::1000:1000
    restart: on-failure


volumes:
  data:
  media:
  pgdata:
  redisdata:

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
  traefik_backbone:
    name: traefik_backbone
    external: true